### ISSUE TITLE
Trouble installing R POT

### ISSUE THREAD

**Issue by kellieotto** [iagolemos1/thresholdmodeling#3] opened 2020-01-23 19:32 UTC
I cannot import thresholdmodeling because I'm having trouble with installing POT. I tried this on my personal laptop and on my work laptop in a docker container that's set up with limited Python packages. 

This is the error I got:

```
* installing *source* package ‘POT’ ...
** package ‘POT’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
x86_64-conda_cos6-linux-gnu-cc -I"/opt/conda/envs/py3-primary/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/opt/conda/envs/py3-primary/include -Wl,-rpath-link,/opt/conda/envs/py3-primary/lib  -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/opt/conda/envs/py3-primary/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/opt/conda/envs/py3-primary=/usr/local/src/conda-prefix  -c POT.c -o POT.o
/bin/sh: 1: x86_64-conda_cos6-linux-gnu-cc: not found
/opt/conda/envs/py3-primary/lib/R/etc/Makeconf:168: recipe for target 'POT.o' failed
make: *** [POT.o] Error 127
ERROR: compilation failed for package ‘POT’
```

**Comment by iagolemos1** [comment] 2020-01-23 19:50
I don't recognize this error. My previous experiences were using my personal laptop and my work desktop and everything went very well (I am using Windows on that). I am going to try to find out what's happening.

**Comment by kellieotto** [comment] 2020-01-23 19:57
Thanks for looking into it @iagolemos1 . @bahung do you run into problems installing?

**Comment by iagolemos1** [comment] 2020-01-23 20:28
Sorry, my mistake @kellieotto, just forgot to say to install R on your conda env. 
I ran this on linux terminal: 
```
conda activate my_env (your env name)
conda install r
```
After that, R will be installed. 
Since it's installed, everything will works. 
I am going to fix the installation's instructions.

**Comment by iagolemos1** [comment] 2020-01-23 20:41
It is possible to find a new tutorial in the README. Sorry again.

**Comment by iagolemos1** [comment] 2020-01-23 22:02
@kellieotto Do you use macOS? You just need to install R on your environment using the following command line after activating your env:
```conda install r``` 
I put a tutorial on README for Windows and Linux (I don't have acess to macOS, but I believe that knowing that you must install R on your env is enough).

**Comment by bahung** [comment] 2020-01-24 01:02
@kellieotto @iagolemos1 
I ran to the same problem in the first try:

`Complete output (1 lines):
    There is no R_HOME and the R executable cannot be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Then with administrator privilege, I installed r base with command: `conda install r`
then `pip install thresholdmodeling`

This error follows:
`ERROR: Command errored out with exit status 1:
     command: ...\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hungba\\AppData\\Local\\Temp\\pip-install-eevqhowv\\rpy2\\setup.py'"'"'; __file__='"'"'C:\\Users\\hungba\\AppData\\Local\\Temp\\pip-install-eevqhowv\\rpy2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\hungba\AppData\Local\Temp\pip-install-eevqhowv\rpy2\pip-egg-info'
         cwd: C:\Users\hungba\AppData\Local\Temp\pip-install-eevqhowv\rpy2\
    Complete output (17 lines):
    'sh' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hungba\AppData\Local\Temp\pip-install-eevqhowv\rpy2\setup.py", line 105, in <module>
        c_extension_status = get_r_c_extension_status()
      File "C:\Users\hungba\AppData\Local\Temp\pip-install-eevqhowv\rpy2\setup.py", line 94, in get_r_c_extension_status
        *situation.get_r_flags(r_home, '--ldflags')
      File "C:\Users\hungba\AppData\Local\Temp\pip-install-eevqhowv\rpy2\rpy2\situation.py", line 176, in get_r_flags
        allow_empty=False)))
      File "C:\Users\hungba\AppData\Local\Temp\pip-install-eevqhowv\rpy2\rpy2\situation.py", line 145, in _get_r_cmd_config
        universal_newlines=True
      File "C:\ProgramData\Anaconda3\envs\TextualSEC\lib\subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "C:\ProgramData\Anaconda3\envs\TextualSEC\lib\subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '('C:\\ProgramData\\Anaconda3\\envs\\TextualSEC\\lib\\R\\bin\\x64\\R', 'CMD', 'config', '--ldflags')' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by iagolemos1** [comment] 2020-01-24 01:17
I really don't understading what may be happening. I installed the package in my new Ubuntu OS just after @kellieotto open the issue. 
@bahung Did you try exactly what I wrote in the README?

**Comment by iagolemos1** [comment] 2020-01-24 01:27
@bahung what seems to me you are having problems to install the rpy2 package. I found something, with a different package on internet (which should be installed also with pip install) in this [link](https://stackoverflow.com/questions/57444207/how-to-fix-error-error-command-errored-out-with-exit-status-1-python-when-t). There are solutions in there. I don't know what is happening, maybe your Python version? Anaconda version?

**Comment by bahung** [comment] 2020-01-24 01:42
The problem is windows user usually not have `sh`. I download rpy2 wheel and install directly. Your package is now successfully installed.
Thanks.

**Comment by iagolemos1** [comment] 2020-01-24 01:44
You are welcome. I am very happy. @bahung but this sh problem is not normal. I installed everything in my two windows machines. I am going to try to find out why this is happening, since It should install normally.

**Comment by iagolemos1** [comment] 2020-01-24 11:49
@bahung Just to clarify, I was reading on the rpy2 documentation and it does not support Windows because of lack of resources. There are two main ways to install rpy2 then, the same you did and by using [Anaconda Repository](https://anaconda.org/r/rpy2). I installed by Anaconda Repository the first time. The tutorial in README is updated.

@kellieotto If you have problems like that if you are using MacOS, let me know. I will try to solve this and find out the best way for installing tha package on this operational system.

**Comment by kellieotto** [comment] 2020-01-24 17:59
@iagolemos1 Now I can install `POT` and import `thresholdmodeling` on my work machine. Thanks!

I'm still having trouble on my personal laptop, but I think this is a MacOS/XCode issue. I get an error saying the stdio.h file cannot be found. I'm having trouble resolving the problem, but it's outside the scope of your package :P

**Closed as completed** 2020-01-24 18:01 UTC
